version: "3.9"

services: 
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment: 
      - PUID=1000
      - PGID=1000
    volumes: 
      - /home/santana/Desktop/studies/hotel/mongodb/database:/data/db
    ports: 
      - 27017:27017
    restart: unless-stopped